# Generated by Django 4.0.2 on 2022-02-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='private_key',
            field=models.TextField(),
        ),
    ]
