# Generated by Django 4.0.2 on 2022-02-03 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('address', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=50)),
                ('chainId', models.IntegerField()),
                ('decimals', models.PositiveIntegerField()),
                ('logoURI', models.URLField(blank=True, max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_from', models.DecimalField(decimal_places=30, max_digits=50)),
                ('count_to', models.DecimalField(decimal_places=30, max_digits=50)),
                ('sell_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('slippage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.TextField(blank=True)),
                ('only_buy', models.BooleanField(default=False)),
                ('is_revolving_trade', models.BooleanField(default=False)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('_password', models.CharField(blank=True, max_length=50)),
                ('token_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_from', to='order.coin')),
                ('token_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_to', to='order.coin')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='authentication.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=500)),
                ('type_tx', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale')], default='purchase', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txs', to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.DecimalField(decimal_places=30, max_digits=50)),
                ('close', models.DecimalField(decimal_places=30, max_digits=50)),
                ('max_price', models.DecimalField(decimal_places=30, max_digits=50)),
                ('min_price', models.DecimalField(decimal_places=30, max_digits=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='order.order')),
            ],
        ),
    ]
