# Generated by Django 4.0 on 2021-12-17 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='from_count',
            new_name='count_from',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='to_count',
            new_name='count_to',
        ),
    ]
