# Generated by Django 4.0 on 2021-12-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contract_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
