# Generated by Django 4.0.1 on 2022-01-20 14:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderprice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 20, 14, 20, 45, 896527, tzinfo=utc)),
        ),
    ]
