# Generated by Django 4.0 on 2021-12-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_contract_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='task_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
