# Generated by Django 4.0 on 2021-12-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_status_alter_order_contract_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='task_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
